---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Speaker pHAT"
  org.opencontainers.image.description: "Use the Pimoroni Speaker pHAT as a sound output on your HA Rapsberry Pi."
  org.opencontainers.image.source: "https://github.com/ajwatt/speakerphat"
  org.opencontainers.image.licenses: "Apache License 2.0"
